spring:
  application:
    name: reward-calculator
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rewarddb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12341234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    defer-datasource-initialization: true
server:
  port: 8081
